name: Build & Release Binaries

on:
  release:
    types: [published]

jobs:
  build:
    name: Build for ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install pyinstaller
        run: pip install pyinstaller

      - name: Build binary
        run: |
          cd src
          pyinstaller --onefile main.py --name love-pm

      - name: Upload to GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            src/dist/love-pm*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
